"""Volume meshing layer for the RoboCAD deep solver pipeline (Phase 28C).

Wraps optional Gmsh / Netgen tetrahedral meshers, writes OpenFOAM
``blockMesh`` / ``snappyHexMesh`` case-directory stubs, and keeps the Phase 28A
compatibility helpers ``generate_volume_mesh`` and ``write_vtk_mesh`` used by
the solver adapters.

Real solver tools are optional; when missing, the layer returns a
``MeshResult`` with a clear error, while the adapter-level fallback path still
produces a coarse tetrahedralization.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import numpy as np
import trimesh


try:
    from build123d import Shape
except Exception:  # pragma: no cover
    Shape = None  # type: ignore[misc,assignment]


# ---------------------------------------------------------------------------
# Phase 28C result dataclass
# ---------------------------------------------------------------------------


@dataclass
class MeshResult:
    """Result of a volume meshing pass."""

    success: bool
    mesh_path: Optional[Path] = None
    format: str = ""
    solver_case_path: Optional[Path] = None
    solver: str = ""
    errors: list[str] = field(default_factory=list)
    details: dict[str, Any] = field(default_factory=dict)

    def model_dump(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "mesh_path": str(self.mesh_path) if self.mesh_path else None,
            "format": self.format,
            "solver_case_path": str(self.solver_case_path) if self.solver_case_path else None,
            "solver": self.solver,
            "errors": self.errors,
            "details": self.details,
        }


# ---------------------------------------------------------------------------
# Phase 28C helpers
# ---------------------------------------------------------------------------


def _surface_mesh_from_input(shape_or_mesh: Any) -> tuple[Optional[trimesh.Trimesh], list[str]]:
    """Normalize a build123d Shape or trimesh.Trimesh into a surface mesh."""
    if isinstance(shape_or_mesh, trimesh.Trimesh):
        return shape_or_mesh, []

    if Shape is not None and isinstance(shape_or_mesh, Shape):
        try:
            raw_vertices, raw_faces = shape_or_mesh.tessellate(0.01)
            verts = np.array(
                [[float(v.X), float(v.Y), float(v.Z)] for v in raw_vertices],
                dtype=float,
            )
            faces = np.asarray(raw_faces, dtype=int)
            mesh = trimesh.Trimesh(vertices=verts, faces=faces, process=True)
            mesh.fix_normals()
            mesh.merge_vertices()
            return mesh, []
        except Exception as exc:
            return None, [f"Failed to tessellate shape: {exc}"]

    return None, [f"Unsupported input type: {type(shape_or_mesh)}"]


def _write_openfoam_blockmesh_dict(path: Path, mesh_filename: str) -> None:
    """Write a minimal OpenFOAM ``blockMeshDict`` stub."""
    lines = [
        "/*--------------------------------*- C++ -*----------------------------------*\\",
        "| OpenFOAM blockMeshDict stub generated by RoboCAD Phase 28C                |",
        "\\*---------------------------------------------------------------------------*/",
        "FoamFile",
        "{",
        "    version     2.0;",
        "    format      ascii;",
        "    class       dictionary;",
        "    object      blockMeshDict;",
        "}",
        "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //",
        "convertToMeters 1.0;",
        "",
        "vertices",
        "(",
        "    ( -1 -1 -1 )",
        "    (  1 -1 -1 )",
        "    (  1  1 -1 )",
        "    ( -1  1 -1 )",
        "    ( -1 -1  1 )",
        "    (  1 -1  1 )",
        "    (  1  1  1 )",
        "    ( -1  1  1 )",
        ");",
        "",
        "blocks",
        "(",
        "    hex (0 1 2 3 4 5 6 7) (20 20 20) simpleGrading (1 1 1)",
        ");",
        "",
        "edges",
        "(",
        ");",
        "",
        "boundary",
        "(",
        "    wall",
        "    {",
        "        type wall;",
        "        faces",
        "        (",
        "        );",
        "    }",
        ");",
        "",
        "// ************************************************************************* //",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_openfoam_snappy_dict(path: Path, mesh_filename: str) -> None:
    """Write a minimal OpenFOAM ``snappyHexMeshDict`` stub."""
    lines = [
        "/*--------------------------------*- C++ -*----------------------------------*\\",
        "| OpenFOAM snappyHexMeshDict stub generated by RoboCAD Phase 28C          |",
        "\\*---------------------------------------------------------------------------*/",
        "FoamFile",
        "{",
        "    version     2.0;",
        "    format      ascii;",
        "    class       dictionary;",
        "    object      snappyHexMeshDict;",
        "}",
        "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //",
        "",
        "castellatedMesh true;",
        "snap            true;",
        "addLayers       false;",
        "",
        "geometry",
        "(",
        "    {",
        f"        name {mesh_filename};",
        f"        file \"{mesh_filename}\";",
        "        type triSurfaceMesh;",
        "    }",
        ");",
        "",
        "// ************************************************************************* //",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_openfoam_case_dir(
    shape_or_mesh: Any,
    output_dir: Path | str,
    mesh_filename: str = "surface_mesh.stl",
) -> MeshResult:
    """Generate an OpenFOAM case directory with ``blockMesh`` / ``snappyHexMesh`` stubs.

    Exports the input surface mesh as an STL into the case directory, then writes
    the required OpenFOAM dictionary files. This does not run any OpenFOAM
    binaries; it produces a simulation-ready starting point.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    errors: list[str] = []

    surface_mesh, input_errors = _surface_mesh_from_input(shape_or_mesh)
    if surface_mesh is None:
        return MeshResult(
            success=False,
            errors=input_errors,
            details={"stage": "input_validation"},
        )

    surface_mesh.fix_normals()
    surface_mesh.merge_vertices()
    stl_path = output_dir / mesh_filename
    try:
        surface_mesh.export(str(stl_path))
    except Exception as exc:
        errors.append(f"Failed to export surface STL: {exc}")

    system_dir = output_dir / "system"
    constant_dir = output_dir / "constant"
    polymesh_dir = constant_dir / "polyMesh"
    zero_dir = output_dir / "0"
    for d in (system_dir, constant_dir, polymesh_dir, zero_dir):
        d.mkdir(parents=True, exist_ok=True)

    try:
        _write_openfoam_blockmesh_dict(system_dir / "blockMeshDict", mesh_filename)
        _write_openfoam_snappy_dict(system_dir / "snappyHexMeshDict", mesh_filename)
    except Exception as exc:
        errors.append(f"Failed to write OpenFOAM dictionaries: {exc}")

    try:
        readme = [
            "# OpenFOAM case directory generated by RoboCAD Phase 28C",
            "",
            f"Surface mesh: {mesh_filename}",
            "",
            "Suggested pipeline:",
            "  blockMesh",
            "  snappyHexMesh",
            "  simpleFoam (or your chosen solver)",
            "",
            "Use ``ai_cad.solvers.meshing.tetrahedral_mesh`` to generate a true",
            "tetrahedral volume mesh with Gmsh or Netgen if installed.",
        ]
        (output_dir / "README.md").write_text("\n".join(readme) + "\n", encoding="utf-8")
    except Exception as exc:
        errors.append(f"Failed to write README: {exc}")

    success = len(errors) == 0 and stl_path.exists()
    return MeshResult(
        success=success,
        mesh_path=stl_path if stl_path.exists() else None,
        format="stl_surface",
        solver_case_path=output_dir,
        solver="openfoam_stub",
        errors=errors,
        details={
            "surface_vertices": len(surface_mesh.vertices),
            "surface_faces": len(surface_mesh.faces),
        },
    )


def tet_mesh_with_gmsh(
    shape_or_mesh: Any,
    output_dir: Path | str,
    mesh_size: float = 0.1,
) -> MeshResult:
    """Attempt tetrahedral meshing with Gmsh.

    If Gmsh is not importable, returns a graceful error result.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    surface_mesh, input_errors = _surface_mesh_from_input(shape_or_mesh)
    if surface_mesh is None:
        return MeshResult(
            success=False,
            format="msh",
            errors=input_errors,
            details={"stage": "input_validation"},
        )

    try:
        import gmsh
    except ImportError as exc:
        return MeshResult(
            success=False,
            format="msh",
            errors=[f"Gmsh not installed: {exc}"],
            details={"tool": "gmsh", "available": False},
        )

    stl_path = output_dir / "surface_for_gmsh.stl"
    surface_mesh.export(str(stl_path))
    mesh_path = output_dir / "volume_mesh.msh"

    try:
        gmsh.initialize()
        gmsh.model.add("robocad_volume")
        gmsh.merge(str(stl_path))
        gmsh.model.geo.synchronize()

        surfaces = gmsh.model.getEntities(2)
        if surfaces:
            surface_loop = gmsh.model.geo.addSurfaceLoop([s[1] for s in surfaces])
            gmsh.model.geo.addVolume([surface_loop])
            gmsh.model.geo.synchronize()

        gmsh.option.setNumber("Mesh.CharacteristicLengthMin", mesh_size * 0.1)
        gmsh.option.setNumber("Mesh.CharacteristicLengthMax", mesh_size)
        gmsh.model.mesh.generate(2)
        gmsh.model.mesh.generate(3)
        gmsh.write(str(mesh_path))
        gmsh.finalize()

        return MeshResult(
            success=True,
            mesh_path=mesh_path,
            format="msh",
            errors=[],
            details={
                "tool": "gmsh",
                "available": True,
                "surface_vertices": len(surface_mesh.vertices),
                "surface_faces": len(surface_mesh.faces),
            },
        )
    except Exception as exc:
        try:
            gmsh.finalize()
        except Exception:
            pass
        return MeshResult(
            success=False,
            format="msh",
            errors=[f"Gmsh meshing failed: {exc}"],
            details={"tool": "gmsh", "available": True},
        )


def tet_mesh_with_netgen(
    shape_or_mesh: Any,
    output_dir: Path | str,
    mesh_size: float = 0.1,
) -> MeshResult:
    """Attempt tetrahedral meshing with Netgen.

    If Netgen is not importable, returns a graceful error result.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    surface_mesh, input_errors = _surface_mesh_from_input(shape_or_mesh)
    if surface_mesh is None:
        return MeshResult(
            success=False,
            format="vol",
            errors=input_errors,
            details={"stage": "input_validation"},
        )

    try:
        import netgen
        from netgen.meshing import MeshingParameters
        import netgen.occ  # noqa: F401
    except ImportError as exc:
        return MeshResult(
            success=False,
            format="vol",
            errors=[f"Netgen not installed: {exc}"],
            details={"tool": "netgen", "available": False},
        )

    stl_path = output_dir / "surface_for_netgen.stl"
    surface_mesh.export(str(stl_path))
    mesh_path = output_dir / "volume_mesh.vol"

    try:
        geo = netgen.occ.OCCGeometry(str(stl_path))
        mp = MeshingParameters(maxh=mesh_size)
        ng_mesh = geo.GenerateMesh(mp=mp)
        ng_mesh.Save(str(mesh_path))

        return MeshResult(
            success=True,
            mesh_path=mesh_path,
            format="vol",
            errors=[],
            details={
                "tool": "netgen",
                "available": True,
                "surface_vertices": len(surface_mesh.vertices),
                "surface_faces": len(surface_mesh.faces),
            },
        )
    except Exception as exc:
        return MeshResult(
            success=False,
            format="vol",
            errors=[f"Netgen meshing failed: {exc}"],
            details={"tool": "netgen", "available": True},
        )


def tetrahedral_mesh(
    shape_or_mesh: Any,
    output_dir: Path | str,
    mesh_size: float = 0.1,
    prefer: str = "gmsh",
) -> MeshResult:
    """Generate a tetrahedral volume mesh using Gmsh or Netgen.

    Falls back from the preferred mesher to the other when the first is missing
    or fails. If neither is available, returns an error ``MeshResult`` with the
    collected messages.
    """
    if prefer not in ("gmsh", "netgen"):
        return MeshResult(
            success=False,
            errors=[f"Invalid preferred mesher: {prefer}. Choose 'gmsh' or 'netgen'."],
            details={"stage": "configuration"},
        )

    order = ["gmsh", "netgen"] if prefer == "gmsh" else ["netgen", "gmsh"]
    results: list[MeshResult] = []
    for tool in order:
        if tool == "gmsh":
            res = tet_mesh_with_gmsh(shape_or_mesh, output_dir, mesh_size)
        else:
            res = tet_mesh_with_netgen(shape_or_mesh, output_dir, mesh_size)
        if res.success:
            return res
        results.append(res)

    errors = [f"{r.details.get('tool', 'tool')}: {r.errors[0]}" for r in results if r.errors]
    return MeshResult(
        success=False,
        errors=errors,
        details={"attempted": order, "fallback_exhausted": True},
    )


# ---------------------------------------------------------------------------
# Phase 28A compatibility helpers (used by solver adapters)
# ---------------------------------------------------------------------------


def gmsh_available() -> bool:
    """Return True if the Gmsh Python module can be imported."""
    try:
        import gmsh  # noqa: F401
        return True
    except Exception:
        return False


def netgen_available() -> bool:
    """Return True if Netgen Python bindings are available."""
    try:
        import netgen  # noqa: F401
        return True
    except Exception:
        return False


def mesh_info(mesh: trimesh.Trimesh) -> dict[str, Any]:
    """Return a summary dict useful for solver input files."""
    return {
        "vertices": len(mesh.vertices),
        "faces": len(mesh.faces),
        "volume_m3": float(mesh.volume) / 1e9 if mesh.is_watertight else 0.0,
        "bounds_m": mesh.bounds.tolist(),
        "watertight": mesh.is_watertight,
        "is_winding_consistent": mesh.is_winding_consistent,
    }


def write_vtk_mesh(mesh: trimesh.Trimesh, path: Path) -> None:
    """Write a surface mesh to a legacy VTK file for external solvers."""
    with path.open("w", encoding="utf-8") as f:
        f.write("# vtk DataFile Version 3.0\n")
        f.write("RoboCAD surface mesh\n")
        f.write("ASCII\n")
        f.write("DATASET POLYDATA\n")
        f.write(f"POINTS {len(mesh.vertices)} float\n")
        for v in mesh.vertices:
            f.write(f"{v[0]} {v[1]} {v[2]}\n")
        f.write(f"POLYGONS {len(mesh.faces)} {len(mesh.faces) * 4}\n")
        for face in mesh.faces:
            f.write(f"3 {face[0]} {face[1]} {face[2]}\n")


def coarse_tet_mesh(mesh: trimesh.Trimesh) -> dict[str, Any]:
    """Return a minimal fallback tetrahedral mesh from a watertight surface.

    When Gmsh/Netgen are unavailable this approximates the volume with the
    convex hull tetrahedralization from scipy.spatial.Delaunay. The result is
    not boundary-conforming for concave shapes but is enough for integration
    tests and solver file format validation.
    """
    try:
        from scipy.spatial import Delaunay
    except Exception as exc:
        raise RuntimeError("scipy is required for fallback tetrahedral meshing") from exc

    pts = mesh.vertices
    hull = Delaunay(pts)
    return {
        "vertices": hull.points.tolist(),
        "tetrahedra": hull.simplices.tolist(),
        "element_count": len(hull.simplices),
    }


def generate_volume_mesh(
    mesh: trimesh.Trimesh,
    output_dir: Path,
    target_edge_length: float = 1.0,
) -> dict[str, Any]:
    """Generate a volume mesh, preferring Gmsh if available.

    Returns a dict with file paths and mesh statistics. External mesher errors
    fall back to the coarse tetrahedralization.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    surface_vtk = output_dir / "surface.vtk"
    write_vtk_mesh(mesh, surface_vtk)

    if gmsh_available():
        try:
            return _gmsh_tet_mesh(mesh, output_dir, target_edge_length)
        except Exception as exc:
            return {"error": str(exc), "fallback": True, **coarse_tet_mesh(mesh)}

    return {
        "surface_vtk": str(surface_vtk),
        **coarse_tet_mesh(mesh),
    }


def _gmsh_tet_mesh(
    mesh: trimesh.Trimesh,
    output_dir: Path,
    target_edge_length: float,
) -> dict[str, Any]:
    import gmsh

    gmsh.initialize()
    try:
        gmsh.model.add("robocad")
        tags = []
        for v in mesh.vertices:
            tags.append(gmsh.model.geo.addPoint(v[0], v[1], v[2], target_edge_length))
        # Simplified: gmsh requires a full surface/volume definition; this is a
        # placeholder that at least exercises the API without crashing.
        gmsh.model.geo.synchronize()
        gmsh.model.mesh.generate(3)
        msh_path = output_dir / "volume.msh"
        gmsh.write(str(msh_path))
        _, _, elem_tags = gmsh.model.mesh.getElements(dim=3)
        return {
            "surface_vtk": str(output_dir / "surface.vtk"),
            "volume_msh": str(msh_path),
            "element_count": sum(len(t) for t in elem_tags),
        }
    finally:
        gmsh.finalize()
