"""OpenFOAM case builder and lightweight runner for RoboCAD Phase 28C.

This adapter turns a surface mesh (``trimesh.Trimesh``) and a boundary-condition
dictionary into a complete OpenFOAM incompressible-flow case.  If OpenFOAM is
available locally (or via Docker when requested) it will run the standard
``blockMesh`` → ``snappyHexMesh`` → ``simpleFoam`` pipeline; otherwise it writes
the case files and returns gracefully.  After a run it parses drag/lift from
``forceCoeffs`` / ``forces`` post-processing files when they exist.
"""
from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Optional

import numpy as np
import trimesh


__all__ = [
    "OpenFOAMCaseResult",
    "build_openfoam_case",
    "run_openfoam_case",
    "parse_force_coefficients",
]


@dataclass
class OpenFOAMCaseResult:
    """Result object returned by the OpenFOAM adapter."""

    success: bool = False
    case_dir: Optional[Path] = None
    files_written: list[str] = field(default_factory=list)
    openfoam_detected: bool = False
    run_success: Optional[bool] = None
    coefficients: dict[str, Any] = field(default_factory=dict)
    errors: list[str] = field(default_factory=list)
    details: dict[str, Any] = field(default_factory=dict)

    def model_dump(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "case_dir": str(self.case_dir) if self.case_dir else None,
            "files_written": self.files_written,
            "openfoam_detected": self.openfoam_detected,
            "run_success": self.run_success,
            "coefficients": self.coefficients,
            "errors": self.errors,
            "details": self.details,
        }


def _foam_header(object_name: str, class_name: str) -> str:
    return f"""/* OpenFOAM file generated by RoboCAD Phase 28C */
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {class_name};
    object      {object_name};
}}
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //"""


def _format_uniform(value: Any) -> str:
    if isinstance(value, (list, tuple, np.ndarray)):
        vals = []
        for v in value:
            f = float(v)
            if abs(f) < 1e-9:
                f = 0.0
            vals.append(str(round(f, 9)))
        return f"uniform ({' '.join(vals)})"
    return f"uniform {float(value)}"


def _write_block_mesh_dict(
    path: Path,
    bounds: tuple[tuple[float, float, float], tuple[float, float, float]],
    cells: tuple[int, int, int] = (30, 30, 30),
) -> None:
    """Write a hex background mesh that encloses the surface bounding box."""
    (xmin, ymin, zmin), (xmax, ymax, zmax) = bounds
    vertices = [
        (xmin, ymin, zmin),  # 0
        (xmax, ymin, zmin),  # 1
        (xmax, ymax, zmin),  # 2
        (xmin, ymax, zmin),  # 3
        (xmin, ymin, zmax),  # 4
        (xmax, ymin, zmax),  # 5
        (xmax, ymax, zmax),  # 6
        (xmin, ymax, zmax),  # 7
    ]
    verts_str = "\n".join(f"        ( {x} {y} {z} )" for x, y, z in vertices)
    nx, ny, nz = cells

    content = f"""{_foam_header("blockMeshDict", "dictionary")}

convertToMeters 1.0;

vertices
(
{verts_str}
);

blocks
(
    hex (0 1 2 3 4 5 6 7) ({nx} {ny} {nz}) simpleGrading (1 1 1)
);

edges
(
);

boundary
(
    inlet
    {{
        type patch;
        faces
        (
            (0 4 7 3)
        );
    }}
    outlet
    {{
        type patch;
        faces
        (
            (1 2 6 5)
        );
    }}
    bottom
    {{
        type patch;
        faces
        (
            (0 1 5 4)
        );
    }}
    top
    {{
        type patch;
        faces
        (
            (3 7 6 2)
        );
    }}
    front
    {{
        type patch;
        faces
        (
            (0 3 2 1)
        );
    }}
    back
    {{
        type patch;
        faces
        (
            (4 5 6 7)
        );
    }}
);

mergePatchPairs
(
);

// ************************************************************************* //"""
    path.write_text(content + "\n", encoding="utf-8")


def _write_snappy_hex_mesh_dict(path: Path, mesh_name: str) -> None:
    content = f"""{_foam_header("snappyHexMeshDict", "dictionary")}

castellatedMesh true;
snap true;
addLayers false;

geometry
{{
    model
    {{
        type triSurfaceMesh;
        file "constant/triSurface/{mesh_name}";
    }}
}}

castellatedMeshControls
{{
    maxLocalCells       1000000;
    maxGlobalCells      2000000;
    minRefinementCells  0;
    maxLoadUnbalance    0.10;
    nCellsBetweenLevels 1;

    features
    (
    );

    refinementSurfaces
    {{
        model
        {{
            level (2 2);
            patchInfo
            {{
                type wall;
            }}
        }}
    }}

    resolveFeatureAngle 30;

    refinementRegions
    (
    );

    locationInMesh (0 0 0);
    allowFreeStandingZoneFaces true;
}}

snapControls
{{
    nSmoothPatch    3;
    tolerance       1.0;
    nSolveIter      30;
    nRelaxIter      5;
    nFeatureSnapIter 10;
    implicitFeatureSnap false;
    explicitFeatureSnap true;
    multiRegionFeatureSnap false;
}}

addLayersControls
{{
    relativeSizes true;
    expansionRatio 1.0;
    finalLayerThickness 0.3;
    minThickness 0.1;
    nGrow 0;
    featureAngle 60;
    slipFeatureAngle 30;
    nRelaxedIter 10;
}}

meshQualityControls
{{
    maxNonOrtho 70;
    maxBoundarySkewness 4;
    maxInternalSkewness 4;
    maxConcave 80;
    minVol 1e-13;
    minTetQuality 1e-15;
    minArea -1;
    minTwist 0.02;
    minDeterminant 0.001;
    minFaceWeight 0.02;
    minVolRatio 0.01;
    minTriangleTwist -1;
    nSmoothScale 4;
    errorReduction 0.75;
}}

// ************************************************************************* //"""
    path.write_text(content + "\n", encoding="utf-8")


def _write_field_file(
    path: Path,
    field: str,
    class_name: str,
    dimensions: list[int],
    internal_value: Any,
    boundary_conditions: dict[str, dict[str, Any]],
) -> None:
    lines = [_foam_header(field, class_name), ""]
    lines.append("dimensions")
    lines.append(f"    ({' '.join(str(d) for d in dimensions)});")
    lines.append("")
    lines.append("internalField")
    lines.append(f"    {_format_uniform(internal_value)};")
    lines.append("")
    lines.append("boundaryField")
    lines.append("(")
    for patch, spec in boundary_conditions.items():
        field_spec = spec.get(field, {})
        ptype = field_spec.get("type", "zeroGradient")
        lines.append(f"    {patch}")
        lines.append("    {")
        lines.append(f"        type {ptype};")
        if "value" in field_spec:
            lines.append(f"        value {_format_uniform(field_spec['value'])};")
        lines.append("    }")
    lines.append(");")
    lines.append("")
    lines.append("// ************************************************************************* //")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_control_dict(
    path: Path,
    solver: str,
    reference_values: dict[str, float],
    write_force_coeffs: bool,
) -> None:
    flow_velocity = reference_values.get("flow_velocity_ms", 10.0)
    l_ref = reference_values.get("characteristic_length_m", 1.0)
    a_ref = reference_values.get("reference_area_m2", l_ref * l_ref)
    rho = reference_values.get("density_kg_m3", 1.225)

    functions = ""
    if write_force_coeffs:
        functions = f"""
functions
{{
    forceCoeffs
    {{
        type            forceCoeffs;
        libs            (forces);
        writeControl    timeStep;
        writeInterval   10;
        log             true;
        patches         (model);
        rhoInf          {rho};
        CofR            (0 0 0);
        liftDir         (0 0 1);
        dragDir         (1 0 0);
        pitchAxis       (0 1 0);
        magUInf         {flow_velocity};
        lRef            {l_ref};
        Aref            {a_ref};
    }}

    forces
    {{
        type            forces;
        libs            (forces);
        writeControl    timeStep;
        writeInterval   10;
        log             true;
        patches         (model);
        rhoInf          {rho};
        CofR            (0 0 0);
    }}
}}
"""

    content = f"""{_foam_header("controlDict", "dictionary")}

application     {solver};

startFrom       startTime;

startTime       0;

stopAt          endTime;

endTime         500;

deltaT          1;

writeControl    timeStep;

writeInterval   100;

purgeWrite      2;

writeFormat     ascii;

writePrecision  6;

writeCompression off;

timeFormat      general;

timePrecision   6;

runTimeModifiable true;
{functions}
// ************************************************************************* //"""
    path.write_text(content + "\n", encoding="utf-8")


def _write_fv_schemes(path: Path) -> None:
    content = f"""{_foam_header("fvSchemes", "dictionary")}

ddtSchemes
{{
    default         steadyState;
}}

gradSchemes
{{
    default         Gauss linear;
    grad(U)         Gauss linear;
}}

divSchemes
{{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,k)      bounded Gauss upwind;
    div(phi,omega)  bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}}

laplacianSchemes
{{
    default         Gauss linear corrected;
}}

interpolationSchemes
{{
    default         linear;
}}

snGradSchemes
{{
    default         corrected;
}}

fluxRequired
{{
    default         no;
    p               ;
}}

// ************************************************************************* //"""
    path.write_text(content + "\n", encoding="utf-8")


def _write_fv_solution(path: Path) -> None:
    content = f"""{_foam_header("fvSolution", "dictionary")}

solvers
{{
    p
    {{
        solver          GAMG;
        tolerance       1e-07;
        relTol          0.1;
        smoother        GaussSeidel;
        nPreSweeps      0;
        nPostSweeps     2;
        cacheAgglomeration on;
        agglomerator    faceAreaPair;
        mergeLevels     1;
    }}

    U
    {{
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-08;
        relTol          0.1;
        nSweeps         1;
    }}
}}

SIMPLE
{{
    nNonOrthogonalCorrectors 0;

    residualControl
    {{
        p               1e-3;
        U               1e-4;
    }}
}}

relaxationFactors
{{
    fields
    {{
        p               0.3;
    }}

    equations
    {{
        U               0.7;
    }}
}}

// ************************************************************************* //"""
    path.write_text(content + "\n", encoding="utf-8")


def _write_transport_properties(path: Path, reference_values: dict[str, float]) -> None:
    nu = reference_values.get("kinematic_viscosity_m2_s", 1.5e-5)
    content = f"""{_foam_header("transportProperties", "dictionary")}

transportModel  Newtonian;

nu              nu [0 2 -1 0 0 0 0] {nu};

// ************************************************************************* //"""
    path.write_text(content + "\n", encoding="utf-8")


def _write_turbulence_properties(path: Path) -> None:
    content = f"""{_foam_header("turbulenceProperties", "dictionary")}

simulationType  laminar;

// ************************************************************************* //"""
    path.write_text(content + "\n", encoding="utf-8")


def _local_openfoam_available(solver: str = "simpleFoam") -> bool:
    return shutil.which("blockMesh") is not None and shutil.which(solver) is not None


def _docker_available() -> bool:
    return shutil.which("docker") is not None


def build_openfoam_case(
    surface_mesh: trimesh.Trimesh,
    case_dir: Path | str,
    boundary_conditions: dict[str, dict[str, Any]],
    reference_values: Optional[dict[str, float]] = None,
    mesh_name: str = "model.stl",
    domain_scale: float = 5.0,
    mesh_scale: float = 1.0,
    background_cells: tuple[int, int, int] = (30, 30, 30),
    solver: str = "simpleFoam",
    write_force_coeffs: bool = True,
) -> OpenFOAMCaseResult:
    """Create a complete OpenFOAM case from a surface mesh.

    Parameters
    ----------
    surface_mesh:
        Watertight surface mesh (e.g. a wing or vehicle body).  Units are
        taken as meters unless ``mesh_scale`` is used to rescale.
    case_dir:
        Directory that will hold the OpenFOAM case.
    boundary_conditions:
        Per-patch boundary specification.  Expected shape::

            {"patchName": {"p": {"type": "zeroGradient"},
                           "U": {"type": "fixedValue", "value": [10, 0, 0]}}}
    reference_values:
        Optional flow reference data.  Recognised keys: ``flow_velocity_ms``,
        ``angle_of_attack_deg``, ``characteristic_length_m``,
        ``reference_area_m2``, ``density_kg_m3``,
        ``kinematic_viscosity_m2_s``.
    mesh_name:
        Name of the exported surface STL inside ``constant/triSurface``.
    domain_scale:
        Multiplier used to size the background blockMesh domain relative to
        the surface bounding-box diagonal.
    mesh_scale:
        Scale factor applied to ``surface_mesh`` before export (e.g. ``0.001``
        to convert millimetres to metres).
    background_cells:
        Number of background hexahedral cells in (x, y, z).
    solver:
        Incompressible-flow solver to declare in ``controlDict``.
    write_force_coeffs:
        If ``True``, add ``forceCoeffs`` / ``forces`` function objects to
        ``controlDict`` so drag/lift can be parsed after the run.

    Returns
    -------
    OpenFOAMCaseResult
        ``success`` is ``True`` when all required files were written.
        ``run_success`` is ``None`` because no solver execution is attempted.
    """
    errors: list[str] = []
    files_written: list[str] = []
    case_dir = Path(case_dir)

    if reference_values is None:
        reference_values = {}

    # Work on a copy so the caller's mesh is not mutated.
    mesh = surface_mesh.copy()
    if mesh_scale != 1.0:
        try:
            mesh.apply_scale(mesh_scale)
        except Exception as exc:
            errors.append(f"Failed to scale mesh: {exc}")

    try:
        case_dir.mkdir(parents=True, exist_ok=True)
        system_dir = case_dir / "system"
        constant_dir = case_dir / "constant"
        tri_surface_dir = constant_dir / "triSurface"
        zero_dir = case_dir / "0"
        system_dir.mkdir(parents=True, exist_ok=True)
        constant_dir.mkdir(parents=True, exist_ok=True)
        tri_surface_dir.mkdir(parents=True, exist_ok=True)
        zero_dir.mkdir(parents=True, exist_ok=True)
    except Exception as exc:
        errors.append(f"Failed to create case directories: {exc}")
        return OpenFOAMCaseResult(
            success=False,
            case_dir=case_dir,
            errors=errors,
            details={"boundary_patches": list(boundary_conditions.keys())},
        )

    # Export surface STL.
    stl_path = tri_surface_dir / mesh_name
    try:
        mesh.export(str(stl_path))
        files_written.append(str(stl_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to export surface STL: {exc}")

    # Background domain around the scaled mesh.
    try:
        bounds = mesh.bounds
        lower, upper = bounds[0].tolist(), bounds[1].tolist()
        diag = float(np.linalg.norm(np.array(upper) - np.array(lower)))
        if diag <= 0.0:
            diag = 1.0
        margin = diag * (domain_scale - 1.0) / 2.0
        domain_bounds = (
            (lower[0] - margin, lower[1] - margin, lower[2] - margin),
            (upper[0] + margin, upper[1] + margin, upper[2] + margin),
        )
    except Exception as exc:
        errors.append(f"Failed to compute domain bounds: {exc}")
        domain_bounds = ((-1.0, -1.0, -1.0), (1.0, 1.0, 1.0))

    # Reference flow values.
    flow_velocity_ms = float(reference_values.get("flow_velocity_ms", 10.0))
    aoa_deg = float(reference_values.get("angle_of_attack_deg", 0.0))
    aoa_rad = np.radians(aoa_deg)
    internal_u = [
        float(flow_velocity_ms * np.cos(aoa_rad)),
        float(flow_velocity_ms * np.sin(aoa_rad)),
        0.0,
    ]

    # System dictionaries.
    block_mesh_path = system_dir / "blockMeshDict"
    try:
        _write_block_mesh_dict(block_mesh_path, domain_bounds, background_cells)
        files_written.append(str(block_mesh_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to write blockMeshDict: {exc}")

    snappy_path = system_dir / "snappyHexMeshDict"
    try:
        _write_snappy_hex_mesh_dict(snappy_path, mesh_name)
        files_written.append(str(snappy_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to write snappyHexMeshDict: {exc}")

    control_path = system_dir / "controlDict"
    try:
        _write_control_dict(control_path, solver, reference_values, write_force_coeffs)
        files_written.append(str(control_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to write controlDict: {exc}")

    fv_schemes_path = system_dir / "fvSchemes"
    try:
        _write_fv_schemes(fv_schemes_path)
        files_written.append(str(fv_schemes_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to write fvSchemes: {exc}")

    fv_solution_path = system_dir / "fvSolution"
    try:
        _write_fv_solution(fv_solution_path)
        files_written.append(str(fv_solution_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to write fvSolution: {exc}")

    transport_path = constant_dir / "transportProperties"
    try:
        _write_transport_properties(transport_path, reference_values)
        files_written.append(str(transport_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to write transportProperties: {exc}")

    turbulence_path = constant_dir / "turbulenceProperties"
    try:
        _write_turbulence_properties(turbulence_path)
        files_written.append(str(turbulence_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to write turbulenceProperties: {exc}")

    # Initial fields.
    p_path = zero_dir / "p"
    u_path = zero_dir / "U"
    try:
        _write_field_file(
            p_path,
            "p",
            "volScalarField",
            [0, 2, -2, 0, 0, 0, 0],
            reference_values.get("internal_pressure", 0.0),
            boundary_conditions,
        )
        files_written.append(str(p_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to write p boundary file: {exc}")

    try:
        _write_field_file(
            u_path,
            "U",
            "volVectorField",
            [0, 1, -1, 0, 0, 0, 0],
            internal_u,
            boundary_conditions,
        )
        files_written.append(str(u_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to write U boundary file: {exc}")

    # README for manual runs.
    readme_path = case_dir / "README.md"
    try:
        readme = [
            "# OpenFOAM case generated by RoboCAD Phase 28C",
            "",
            f"Surface mesh: constant/triSurface/{mesh_name}",
            f"Solver: {solver}",
            f"Flow velocity: {flow_velocity_ms} m/s",
            f"Angle of attack: {aoa_deg} deg",
            "",
            "Run pipeline:",
            "  blockMesh",
            "  snappyHexMesh -overwrite",
            f"  {solver}",
        ]
        readme_path.write_text("\n".join(readme) + "\n", encoding="utf-8")
        files_written.append(str(readme_path.relative_to(case_dir)))
    except Exception as exc:
        errors.append(f"Failed to write README: {exc}")

    success = len(errors) == 0 and all(
        (case_dir / f).exists() for f in files_written
    )

    return OpenFOAMCaseResult(
        success=success,
        case_dir=case_dir,
        files_written=files_written,
        openfoam_detected=_local_openfoam_available(solver)
        or _docker_available(),
        run_success=None,
        coefficients={},
        errors=errors,
        details={
            "mesh_vertices": len(mesh.vertices),
            "mesh_faces": len(mesh.faces),
            "domain_bounds": domain_bounds,
            "internal_u": internal_u,
            "boundary_patches": list(boundary_conditions.keys()),
        },
    )


def run_openfoam_case(
    case_dir: Path | str,
    solver: str = "simpleFoam",
    use_docker: bool = False,
    docker_image: str = "openfoam/openfoam10-paraview510",
    timeout: int = 1800,
) -> OpenFOAMCaseResult:
    """Run an OpenFOAM case if a runner is available.

    The function first tries a local installation.  If ``use_docker`` is
    ``True`` and Docker is available, it falls back to running inside the
    supplied image.  If neither is available the case is left untouched and
    ``run_success`` is ``False``.

    Parameters
    ----------
    case_dir:
        Existing OpenFOAM case directory.
    solver:
        Flow solver command (``simpleFoam``, ``icoFoam``, etc.).
    use_docker:
        Whether to attempt a Docker-based run when local OpenFOAM is missing.
    docker_image:
        Docker image to use for the Docker path.
    timeout:
        Per-command timeout in seconds.

    Returns
    -------
    OpenFOAMCaseResult
        ``run_success`` is ``True``/``False`` if a runner was attempted, else
        ``None``.  Drag/lift coefficients are parsed when present.
    """
    errors: list[str] = []
    run_success: Optional[bool] = None
    case_dir = Path(case_dir)

    if not case_dir.is_dir():
        errors.append(f"Case directory does not exist: {case_dir}")
        return OpenFOAMCaseResult(
            success=False,
            case_dir=case_dir,
            errors=errors,
        )

    local = _local_openfoam_available(solver)
    docker = use_docker and _docker_available()
    openfoam_detected = local or docker

    if not openfoam_detected:
        return OpenFOAMCaseResult(
            success=True,
            case_dir=case_dir,
            openfoam_detected=False,
            run_success=False,
            coefficients=parse_force_coefficients(case_dir),
            errors=["OpenFOAM not detected (blockMesh/simpleFoam missing); case files written only."],
        )

    commands: list[list[str]] = []
    if local:
        commands = [
            ["blockMesh"],
            ["snappyHexMesh", "-overwrite"],
            [solver],
        ]
    else:
        shell_pipeline = (
            f"blockMesh && snappyHexMesh -overwrite && {solver}"
        )
        commands = [
            [
                "docker",
                "run",
                "--rm",
                "-v",
                f"{case_dir.resolve()}:/case",
                "-w",
                "/case",
                docker_image,
                "bash",
                "-c",
                shell_pipeline,
            ]
        ]

    for cmd in commands:
        log_name = "log." + cmd[0].replace("/", "_")
        log_path = case_dir / log_name
        try:
            result = subprocess.run(
                cmd,
                cwd=case_dir,
                capture_output=True,
                text=True,
                timeout=timeout,
            )
            log_path.write_text(result.stdout + "\n" + result.stderr, encoding="utf-8")
            if result.returncode != 0:
                errors.append(
                    f"Command {' '.join(cmd)} failed with exit {result.returncode}. "
                    f"See {log_name}."
                )
                run_success = False
                break
        except subprocess.TimeoutExpired:
            errors.append(f"Command {' '.join(cmd)} timed out after {timeout}s.")
            run_success = False
            break
        except Exception as exc:
            errors.append(f"Command {' '.join(cmd)} raised {exc}.")
            run_success = False
            break
    else:
        run_success = True

    coefficients = parse_force_coefficients(case_dir)

    return OpenFOAMCaseResult(
        success=run_success is not False,
        case_dir=case_dir,
        openfoam_detected=openfoam_detected,
        run_success=run_success,
        coefficients=coefficients,
        errors=errors,
        details={"commands_attempted": len(commands)},
    )


def parse_force_coefficients(case_dir: Path | str) -> dict[str, Any]:
    """Parse the latest drag/lift values from OpenFOAM post-processing.

    Searches ``postProcessing/forceCoeffs/0/forceCoeffs.dat`` and
    ``postProcessing/forces/0/forces.dat`` and returns the last row values.
    """
    case_dir = Path(case_dir)
    coefficients: dict[str, Any] = {}

    candidates = [
        (case_dir / "postProcessing" / "forceCoeffs" / "0" / "forceCoeffs.dat"),
        (case_dir / "postProcessing" / "forces" / "0" / "forces.dat"),
    ]

    for dat_file in candidates:
        if not dat_file.exists():
            continue
        try:
            text = dat_file.read_text(encoding="utf-8")
        except Exception:
            continue

        lines = [ln.strip() for ln in text.splitlines()]
        header: Optional[list[str]] = None
        data_lines: list[list[str]] = []
        for ln in lines:
            if not ln:
                continue
            if ln.startswith("#"):
                # First comment line is the column header.
                if header is None:
                    header = ln.lstrip("#").split()
                continue
            data_lines.append(ln.split())

        if not data_lines:
            continue

        latest = data_lines[-1]
        if header and len(header) == len(latest):
            for key, raw in zip(header, latest):
                try:
                    coefficients[key] = float(raw)
                except ValueError:
                    coefficients[key] = raw
        elif len(latest) >= 3:
            # Default fallback: time, Cd, Cl.
            try:
                coefficients.setdefault("time", float(latest[0]))
                coefficients.setdefault("Cd", float(latest[1]))
                coefficients.setdefault("Cl", float(latest[2]))
            except ValueError:
                pass

    return coefficients
