"""Professional physics report export for RoboCAD Phase 28E.

Converts a persisted deep verification job result into a readable Markdown
report suitable for engineering review, certification packages, or version-control.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def _fmt(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, float):
        return f"{value:.6g}"
    return str(value)


def _load_metadata(design_dir: Path) -> dict[str, Any]:
    meta_path = design_dir / "metadata.json"
    if meta_path.exists():
        try:
            return json.loads(meta_path.read_text(encoding="utf-8"))
        except Exception:
            pass
    return {}


def _section(title: str, body: str) -> str:
    return f"\n## {title}\n\n{body}\n"


def generate_deep_verify_report(
    design_id: str,
    job_id: str,
    result: dict[str, Any],
    design_dir: Path | None = None,
) -> str:
    """Generate a Markdown report from a deep verification job result."""
    design_dir = design_dir or Path("designs") / design_id
    metadata = _load_metadata(design_dir)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines: list[str] = []
    lines.append(f"# RoboCAD Deep Verification Report")
    lines.append("")
    lines.append(f"- **Design ID:** `{design_id}`")
    lines.append(f"- **Job ID:** `{job_id}`")
    lines.append(f"- **Load case:** {result.get('load_case', '—')}")
    lines.append(f"- **Generated:** {now}")
    lines.append("")

    passed = result.get("passed")
    status = "PASS" if passed else "FAIL" if isinstance(passed, bool) else "UNKNOWN"
    lines.append(f"## Result Summary: {status}")
    lines.append("")

    # Design metadata summary.
    meta_body = ""
    if metadata:
        prompt = metadata.get("prompt", "—")
        domain = metadata.get("domain", "—")
        model = metadata.get("model", "—")
        meta_body += f"- **Prompt:** {prompt}\n"
        meta_body += f"- **Domain:** {domain}\n"
        meta_body += f"- **Generation model:** {model}\n"
    else:
        meta_body = "No design metadata available.\n"
    lines.append(_section("Design Summary", meta_body))

    # Parameters.
    raw = result.get("raw_output", {}) or {}
    details = raw.get("details", {}) or {}
    params_body = ""
    params_body += f"- **Solver:** {raw.get('solver', details.get('solver', '—'))}\n"
    params_body += f"- **Material:** {details.get('material', '—')}\n"
    params_body += f"- **Analysis type:** {raw.get('analysis_type', details.get('analysis_type', '—'))}\n"
    if "node_count" in details:
        params_body += f"- **Analysis nodes:** {details['node_count']}\n"
    if "element_count" in details:
        params_body += f"- **Analysis elements:** {details['element_count']}\n"
    if "boundary_count" in details:
        params_body += f"- **Boundary faces:** {details['boundary_count']}\n"
    lines.append(_section("Solver and Mesh", params_body))

    # Metrics table.
    metrics = result.get("metrics", {}) or {}
    if metrics:
        table = "| Metric | Value |\n| --- | --- |\n"
        for key, value in metrics.items():
            table += f"| {key} | {_fmt(value)} |\n"
        lines.append(_section("Metrics", table))
    else:
        lines.append(_section("Metrics", "No metrics produced.\n"))

    # Failure modes and redesign suggestions.
    failure_modes = result.get("failure_modes", [])
    suggestions = result.get("redesign_suggestions", [])
    if failure_modes:
        lines.append(_section("Failure Modes", "\n".join(f"- {m}" for m in failure_modes)))
    if suggestions:
        lines.append(_section("Redesign Suggestions", "\n".join(f"- {s}" for s in suggestions)))

    # Warnings and errors.
    warnings = result.get("warnings", [])
    errors = result.get("errors", [])
    if warnings:
        lines.append(_section("Warnings", "\n".join(f"- {w}" for w in warnings)))
    if errors:
        lines.append(_section("Errors", "\n".join(f"- {e}" for e in errors)))

    # Solver file paths.
    result_files = raw.get("result_files", {})
    if result_files:
        file_body = "\n".join(f"- **{k}:** `{_fmt(v)}`" for k, v in result_files.items())
        lines.append(_section("Solver Output Files", file_body))

    # Conclusion.
    conclusion = (
        "The design passed the selected load case. Review margins before release."
        if passed
        else "The design did not pass the selected load case. Apply the redesign suggestions and re-run verification."
    )
    lines.append(_section("Engineering Conclusion", conclusion))

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Report generated by RoboCAD Phase 28E deep multi-physics engine.*")

    return "\n".join(lines)


def write_deep_verify_report(
    design_id: str,
    job_id: str,
    result: dict[str, Any],
    output_dir: Path | str,
) -> Path:
    """Write the Markdown report to disk and return its path."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    report_path = output_dir / f"{job_id}_report.md"
    report_path.write_text(
        generate_deep_verify_report(design_id, job_id, result),
        encoding="utf-8",
    )
    return report_path
