"""CFD surface-mesh and solver-stub export for RoboCAD Phase 20.

This module converts generated build123d shapes into surface meshes and writes
lightweight SU2 / OpenFOAM configuration stubs. It follows the same stub pattern
as `ai_cad/fea.py`: real solver execution is intentionally out of scope for
Phase 20; the output is a simulation-ready starting point.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional

import numpy as np
import trimesh


@dataclass
class CFDMeshResult:
    """Result of a CFD surface-mesh export pass."""

    success: bool
    mesh_path: Optional[Path]
    format: str
    solver_config_path: Optional[Path]
    solver: str
    reference_values: dict[str, float]
    errors: list[str]
    details: dict[str, Any]

    def model_dump(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "mesh_path": str(self.mesh_path) if self.mesh_path else None,
            "format": self.format,
            "solver_config_path": str(self.solver_config_path) if self.solver_config_path else None,
            "solver": self.solver,
            "reference_values": self.reference_values,
            "errors": self.errors,
            "details": self.details,
        }


MM_TO_M = 0.001


def _shape_to_trimesh(shape: Any, tolerance: float = 0.01) -> trimesh.Trimesh:
    """Tessellate a build123d shape into a processed trimesh.Trimesh.

    This mirrors the helper in ai_cad.geda_bridge.exporter so the CFD module is
    self-contained and does not depend on the simulation bundle internals.
    """
    raw_vertices, raw_faces = shape.tessellate(tolerance)
    verts = np.array(
        [[float(v.X), float(v.Y), float(v.Z)] for v in raw_vertices],
        dtype=float,
    )
    faces = np.asarray(raw_faces, dtype=int)
    mesh = trimesh.Trimesh(vertices=verts, faces=faces, process=True)
    mesh.fix_normals()
    mesh.merge_vertices()
    return mesh


def _write_su2_config(path: Path, mesh_filename: str, reference_values: dict[str, float]) -> None:
    """Write a minimal SU2 config stub."""
    lines = [
        "% SU2 configuration stub generated by RoboCAD Phase 20",
        f"MESH_FILENAME= {mesh_filename}",
        "MESH_FORMAT= STL",
        "SOLVER= INC_EULER",
        "KIND_TURB_MODEL= NONE",
        f"MACH_NUMBER= {reference_values.get('mach_number', 0.1)}",
        f"AOA= {reference_values.get('angle_of_attack_deg', 0.0)}",
        f"REYNOLDS_NUMBER= {reference_values.get('reynolds_number', 1e5)}",
        "REF_ORIGIN_MOMENT_X= 0.0",
        "REF_ORIGIN_MOMENT_Y= 0.0",
        "REF_ORIGIN_MOMENT_Z= 0.0",
        "REF_LENGTH= 1.0",
        "REF_AREA= 1.0",
        "MARKER_FAR= ( farfield )",
        "MARKER_EULER= ( wall )",
        "MARKER_PLOTTING= ( wall )",
        "MARKER_MONITORING= ( wall )",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_openfoam_stubs(case_dir: Path, mesh_filename: str, reference_values: dict[str, float]) -> None:
    """Write minimal OpenFOAM directory structure and stub files."""
    system_dir = case_dir / "system"
    constant_dir = case_dir / "constant"
    system_dir.mkdir(parents=True, exist_ok=True)
    constant_dir.mkdir(parents=True, exist_ok=True)

    (case_dir / "constant" / "polyMesh").mkdir(parents=True, exist_ok=True)
    (case_dir / "0").mkdir(parents=True, exist_ok=True)

    block_mesh = [
        "/* OpenFOAM blockMeshDict stub generated by RoboCAD Phase 20 */",
        "FoamFile",
        "{",
        "    version     2.0;",
        "    format      ascii;",
        "    class       dictionary;",
        "    object      blockMeshDict;",
        "}",
        "// Stub: replace with a real background mesh for snappyHexMesh.",
        "convertToMeters 1.0;",
        "vertices",
        "(",
        "    ( -1 -1 -1 )",
        "    (  1 -1 -1 )",
        "    (  1  1 -1 )",
        "    ( -1  1 -1 )",
        "    ( -1 -1  1 )",
        "    (  1 -1  1 )",
        "    (  1  1  1 )",
        "    ( -1  1  1 )",
        ");",
        "",
        "blocks",
        "(",
        "    hex (0 1 2 3 4 5 6 7) (20 20 20) simpleGrading (1 1 1)",
        ");",
        "",
        "boundary",
        "(",
        "    wall",
        "    {",
        "        type wall;",
        "        faces",
        "        (",
        "        );",
        "    }",
        ");",
        "",
        "// ************************************************************************* //",
    ]
    (system_dir / "blockMeshDict").write_text("\n".join(block_mesh) + "\n", encoding="utf-8")

    snappy = [
        "/* OpenFOAM snappyHexMeshDict stub generated by RoboCAD Phase 20 */",
        "FoamFile",
        "{",
        "    version     2.0;",
        "    format      ascii;",
        "    class       dictionary;",
        "    object      snappyHexMeshDict;",
        "}",
        f"// Surface STL: {mesh_filename}",
        "geometry",
        "(",
        "    {",
        f"        name {mesh_filename};",
        f"        file \"{mesh_filename}\";",
        "        type triSurfaceMesh;",
        "    }",
        ");",
        "",
        "castellatedMesh true;",
        "snap true;",
        "addLayers false;",
        "",
        "// ************************************************************************* //",
    ]
    (system_dir / "snappyHexMeshDict").write_text("\n".join(snappy) + "\n", encoding="utf-8")

    readme = [
        "# OpenFOAM case stub generated by RoboCAD Phase 20",
        "",
        f"Surface mesh: {mesh_filename}",
        "",
        "Run pipeline:",
        "  blockMesh",
        "  snappyHexMesh",
        "  simpleFoam (or your chosen solver)",
        "",
        f"Reference Mach: {reference_values.get('mach_number', 0.1)}",
        f"Reference AOA: {reference_values.get('angle_of_attack_deg', 0.0)} deg",
    ]
    (case_dir / "README.md").write_text("\n".join(readme) + "\n", encoding="utf-8")


def _export_cfd_mesh_core(
    mesh: trimesh.Trimesh,
    output_dir: Path,
    solver: str,
    angle_of_attack_deg: float,
    flow_velocity_ms: float,
    characteristic_length_m: float,
) -> CFDMeshResult:
    """Shared implementation: write mesh + solver stubs from a trimesh surface mesh."""
    errors: list[str] = []

    # Convert mm internal units to meters for CFD.
    mesh.apply_scale(MM_TO_M)
    mesh.fix_normals()
    mesh.merge_vertices()

    mesh_filename = "surface_mesh.stl"
    mesh_path = output_dir / mesh_filename
    try:
        mesh.export(str(mesh_path))
    except Exception as exc:
        errors.append(f"Failed to export STL: {exc}")
        mesh_path = None

    # Very rough Reynolds estimate.
    kinematic_viscosity = 1.5e-5  # m^2/s for air at room temperature.
    reynolds = (flow_velocity_ms * characteristic_length_m) / kinematic_viscosity
    mach = flow_velocity_ms / 343.0  # speed of sound, m/s.
    reference_values = {
        "mach_number": round(mach, 4),
        "angle_of_attack_deg": float(angle_of_attack_deg),
        "reynolds_number": round(reynolds, 2),
        "flow_velocity_ms": float(flow_velocity_ms),
        "characteristic_length_m": float(characteristic_length_m),
    }

    solver_config_path: Optional[Path] = None
    if solver == "su2_stub":
        solver_config_path = output_dir / "config.cfg"
        _write_su2_config(solver_config_path, mesh_filename, reference_values)
    elif solver == "openfoam_stub":
        case_dir = output_dir / "openfoam_case"
        case_dir.mkdir(parents=True, exist_ok=True)
        _write_openfoam_stubs(case_dir, mesh_filename, reference_values)
        solver_config_path = case_dir
    else:
        errors.append(f"Unknown solver format: {solver}")

    success = mesh_path is not None and solver_config_path is not None

    return CFDMeshResult(
        success=success,
        mesh_path=mesh_path,
        format="stl_surface",
        solver_config_path=solver_config_path,
        solver=solver,
        reference_values=reference_values,
        errors=errors,
        details={
            "mesh_vertices": len(mesh.vertices),
            "mesh_faces": len(mesh.faces),
            "units": "meters",
        },
    )


def export_cfd_mesh(
    shape: Any,
    output_dir: Path | str,
    solver: str = "su2_stub",
    angle_of_attack_deg: float = 0.0,
    flow_velocity_ms: float = 10.0,
    characteristic_length_m: float = 0.1,
) -> CFDMeshResult:
    """Export a surface mesh + solver stub from a build123d Shape."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        mesh = _shape_to_trimesh(shape)
    except Exception as exc:
        return CFDMeshResult(
            success=False,
            mesh_path=None,
            format="stl_surface",
            solver_config_path=None,
            solver=solver,
            reference_values={},
            errors=[f"Failed to tessellate shape: {exc}"],
            details={},
        )

    return _export_cfd_mesh_core(
        mesh,
        output_dir,
        solver,
        angle_of_attack_deg,
        flow_velocity_ms,
        characteristic_length_m,
    )


def export_cfd_mesh_from_stl(
    stl_path: Path | str,
    output_dir: Path | str,
    solver: str = "su2_stub",
    angle_of_attack_deg: float = 0.0,
    flow_velocity_ms: float = 10.0,
    characteristic_length_m: float = 0.1,
) -> CFDMeshResult:
    """Export a surface mesh + solver stub from an existing STL file."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    try:
        mesh = trimesh.load_mesh(str(stl_path))
    except Exception as exc:
        return CFDMeshResult(
            success=False,
            mesh_path=None,
            format="stl_surface",
            solver_config_path=None,
            solver=solver,
            reference_values={},
            errors=[f"Failed to load STL: {exc}"],
            details={},
        )

    if isinstance(mesh, trimesh.Scene):
        if len(mesh.geometry) == 1:
            mesh = next(iter(mesh.geometry.values()))
        else:
            return CFDMeshResult(
                success=False,
                mesh_path=None,
                format="stl_surface",
                solver_config_path=None,
                solver=solver,
                reference_values={},
                errors=["STL scene contains multiple bodies; use a single-body STL."],
                details={},
            )

    mesh.fix_normals()
    mesh.merge_vertices()
    return _export_cfd_mesh_core(
        mesh,
        output_dir,
        solver,
        angle_of_attack_deg,
        flow_velocity_ms,
        characteristic_length_m,
    )
