"""GEDA Bridge — export RoboCAD designs to simulation-ready bundles."""
from __future__ import annotations

from ai_cad.geda_bridge.exporter import (
    compute_inertial,
    export_bundle_from_mesh,
    export_bundle_from_shape,
    export_bundle_from_tree,
    material_density,
    shape_to_trimesh,
)
from ai_cad.geda_bridge.models import (
    BundleManifest,
    BundlePart,
    BundlePaths,
    BundleVerification,
    InertialData,
)
from ai_cad.geda_bridge.packager import package_bundle, package_bundle_paths
from ai_cad.geda_bridge.capabilities import get_capabilities
from ai_cad.geda_bridge.loader import (
    BundleLoadResult,
    load_bundle_into_isaac_sim,
    load_bundle_into_mujoco,
    load_bundle_manifest,
    run_stability_rollout,
    stability_check_bundle,
)
from ai_cad.geda_bridge.runtime_validator import validate_bundle_with_mujoco
from ai_cad.geda_bridge.skill_recommend import recommend_skill, list_skills, SkillRecommendation
from ai_cad.geda_bridge.skill_smoke import PushSkillEnv, TinyMLPPolicy, train_policy_cem, train_push_skill
from ai_cad.geda_bridge.variant_sweep import generate_variants, run_variant_sweep
from ai_cad.geda_bridge.scene_templates import (
    ManipulationScene,
    SceneDescription,
    SceneGoalRegion,
    SceneObject,
    ScenePose,
    bracket_hook_hang_template,
    build_scene,
    export_scene_to_mjcf,
    gripper_cube_grasp_template,
    peg_insertion_template,
    wedge_push_block_template,
)
from ai_cad.geda_bridge.verifier import verify_bundle
from ai_cad.geda_bridge.world_builder import (
    DomainRandomization,
    WorldBuilder,
    WorldDescription,
    WorldSensor,
    WorldTask,
    WorldTerrain,
    apply_domain_randomization,
    box_terrain,
    build_world,
    drone_hover_world_template,
    export_world_to_isaac_json,
    export_world_to_mjcf,
    humanoid_stand_world_template,
    plane_terrain,
    pick_place_world_template,
    push_world_template,
    ramp_terrain,
    resolve_body_alias,
    resolve_world_body_aliases,
    slope_terrain,
    stair_terrain,
    uneven_terrain,
    validate_isaac_world_json,
    walker_world_template,
)
from ai_cad.geda_bridge.world_loaders import (
    load_world_into_isaac_sim,
    load_world_into_mujoco,
    run_world_replay,
)

__all__ = [
    "compute_inertial",
    "export_bundle_from_mesh",
    "export_bundle_from_shape",
    "export_bundle_from_tree",
    "material_density",
    "shape_to_trimesh",
    "BundleManifest",
    "BundlePart",
    "BundlePaths",
    "BundleVerification",
    "InertialData",
    "package_bundle",
    "package_bundle_paths",
    "validate_bundle_with_mujoco",
    "verify_bundle",
    "get_capabilities",
    "recommend_skill",
    "list_skills",
    "SkillRecommendation",
    "PushSkillEnv",
    "TinyMLPPolicy",
    "train_policy_cem",
    "train_push_skill",
    "generate_variants",
    "run_variant_sweep",
    "BundleLoadResult",
    "load_bundle_into_isaac_sim",
    "load_bundle_into_mujoco",
    "load_bundle_manifest",
    "run_stability_rollout",
    "stability_check_bundle",
    "ManipulationScene",
    "SceneDescription",
    "SceneGoalRegion",
    "SceneObject",
    "ScenePose",
    "bracket_hook_hang_template",
    "build_scene",
    "export_scene_to_mjcf",
    "gripper_cube_grasp_template",
    "peg_insertion_template",
    "wedge_push_block_template",
    "DomainRandomization",
    "WorldBuilder",
    "WorldDescription",
    "WorldSensor",
    "WorldTask",
    "WorldTerrain",
    "apply_domain_randomization",
    "box_terrain",
    "build_world",
    "drone_hover_world_template",
    "export_world_to_isaac_json",
    "export_world_to_mjcf",
    "humanoid_stand_world_template",
    "plane_terrain",
    "pick_place_world_template",
    "push_world_template",
    "ramp_terrain",
    "resolve_body_alias",
    "resolve_world_body_aliases",
    "slope_terrain",
    "stair_terrain",
    "uneven_terrain",
    "validate_isaac_world_json",
    "walker_world_template",
    "load_world_into_isaac_sim",
    "load_world_into_mujoco",
    "run_world_replay",
]
